namespace Ryuk.Model.Implementations
{
    public class InternalParameter : IInternalParameter
    {
        public decimal BBGRV { get; set; }
        public decimal RVSATZAN { get; set; }
        public decimal TBSVORV { get; set; }
        public decimal BBGKVPV { get; set; }
        public decimal KVSATZAN { get; set; }
        public decimal KVSATZAG { get; set; }
        public decimal PVSATZAG { get; set; }
        public decimal PVSATZAN { get; set; }
        public decimal W1STKL5 { get; set; }
        public decimal W2STKL5 { get; set; }
        public decimal W3STKL5 { get; set; }
        public decimal GFB { get; set; }
        public decimal SOLZFREI { get; set; }
        public decimal ZRE4J { get; set; }
        public decimal ZVBEZJ { get; set; }
        public decimal JLFREIB { get; set; }
        public decimal JLHINZU { get; set; }
        public int J { get; set; }
        public decimal VBEZB { get; set; }
        public decimal HFVB { get; set; }
        public decimal FVBZ { get; set; }
        public decimal FVB { get; set; }
        public decimal FVBSO { get; set; }
        public decimal FVBZSO { get; set; }
        public decimal HFVBZ { get; set; }
        public decimal HFVBZSO { get; set; }
        public decimal VBEZBSO { get; set; }
        public int KENNVMT { get; set; }
        public decimal ALTE { get; set; }
        public int K { get; set; }
        public decimal BMG { get; set; }
        public decimal HBALTE { get; set; }
        public decimal ZRE4 { get; set; }
        public decimal ZRE4VP { get; set; }
        public decimal ZVBEZ { get; set; }
        public decimal ANP { get; set; }
        public int KZTAB { get; set; }
        public decimal SAP { get; set; }
        public decimal KFB { get; set; }
        public decimal VSP { get; set; }
        public decimal VSPN { get; set; }
        public decimal VSP1 { get; set; }
        public decimal VSP2 { get; set; }
        public decimal VSP3 { get; set; }
        public decimal VHB { get; set; }
        public decimal ZVE { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal ST { get; set; }
        public decimal RW { get; set; }
        public decimal ZZX { get; set; }
        public decimal ZX { get; set; }
        public decimal HOCH { get; set; }
        public decimal VERGL { get; set; }
        public decimal ST1 { get; set; }
        public decimal ST2 { get; set; }
        public decimal DIFF { get; set; }
        public decimal MIST { get; set; }
        public decimal ZTABFB { get; set; }
        public decimal STOVMT { get; set; }
        public decimal LSTJAHR { get; set; }
        public decimal JW { get; set; }
        public decimal ANTEIL1 { get; set; }
        public decimal VKV { get; set; }
        public decimal JBMG { get; set; }
        public decimal SOLZJ { get; set; }
        public decimal SOLZMIN { get; set; }
        public decimal LSTSO { get; set; }
        public decimal LSTOSO { get; set; }
        public decimal SOLZSBMG { get; set; }
        public decimal SOLZSZVE { get; set; }
        public decimal SOLZVBMG { get; set; }
        public decimal LST1 { get; set; }
        public decimal LST2 { get; set; }
        public decimal LST3 { get; set; }
    }
}
