name: testing

on:
  push:
  workflow_dispatch:

permissions: read-all
      
jobs:
  build:
    name: test project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/AK2083/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests 
        run: dotnet test --collect "Code Coverage;Format=cobertura" --no-build --verbosity normal
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-Github-Action@5.2.0
        with:
          reports: './**/TestResults/**/*.cobertura.xml'
          targetdir: '${{ github.workspace }}/coveragereport'
          reporttypes: 'MarkdownSummaryGithub'
      - name: Upload Coverage
        run: cat $GITHUB_WORKSPACE/coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      - name: Archive code
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./**/TestResults/**/*.cobertura.xml
